name: collatz-conjecture
version: 1.2.1.4

dependencies:
  - base

library:
  exposed-modules: CollatzConjecture
  source-dirs: src
  ghc-options: -Wall

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - collatz-conjecture
      - hspec
